Style/Documentation:
  Enabled: false

Style/FileName:
  Exclude:
    - lib/aaf-gumboot.rb

AllCops:
  TargetRubyVersion: 2.1

Metrics/BlockLength:
  Exclude:
    - aaf-gumboot.gemspec
    - spec/**/*.rb
    - lib/**/*.rb
