inherit_from:
  - aaf-rubocop.yml

Style/FileName:
  Exclude:
    - lib/aaf-gumboot.rb

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - spec/**/*.rb
    - lib/tasks/*.rake
    - lib/gumboot/**/*.rb
